[project]
name = "discord-bot"
version = "1.0"
description = ""
authors = ["Wizard Beetle <aaronnicolas1902@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "googletrans>=4.0.2",
    "requests>=2.32.3",
    "python-dotenv>=1.0.0"
]
